Rename workflow to update changelog

diff --git a/.github/workflows/changelog.yaml b/.github/workflows/changelog.yaml
--- a/.github/workflows/changelog.yaml
+++ b/.github/workflows/changelog.yaml
@@ -1,4 +1,36 @@
-- name: Update App Version
+name: Update Changelog
+
+on:
+  push:
+    branches:
+      - master
+  workflow_dispatch:
+
+jobs:
+  fetch-changelog:
+    name: Update Changelog
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      - name: Set HTML File Path
+        run: |
+          HTML_FILE="changelog.html"
+          echo "HTML_FILE=$HTML_FILE" >> $GITHUB_ENV
+
+      - name: Verify HTML File Exists
+        run: |
+          if [ ! -f "$HTML_FILE" ]; then
+            echo "HTML file not found: $HTML_FILE"
+            exit 1
+          fi
+
+          echo "HTML file found:"
+          ls -l "$HTML_FILE"
+
+      - name: Update App Version
         run: |
           APP_VERSION="dummy1"
           TRANSLATIONS="dummy2"
@@ -100,3 +132,9 @@
 
           # Insert Release HEAD section before previous release section
           sed -i "/<h2 id=\"_$EXISTING_APP_VERSION\">Release $EXISTING_APP_VERSION<\/h2>/e cat release_head.html" "$HTML_FILE"
+
+      - name: Upload Changelog Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: changelog
+          path: ${{ env.HTML_FILE }}
